app/containers/TransactionDetail/index.jsx, app/containers/TransactionDetail/reducer.js
+ transaction not found
+ red progress bar on invalid transaction
+ open raw transaction
=> Transaction Detail Feats

app/components/Header/index.jsx
=> fix wiki link

app/components/Transaction/index.jsx, app/components/Transaction/transaction.scss, package.json, yarn.lock
+ Show down arrow in mobile.
+ Now the addresses can be selected.
+ Added copy button to sender & reference addresses for all screen.
=> Phase1 feeddback issues rev2

app/components/CrowdsaleInfo/index.jsx, app/components/FormattedDateTime/FormattedDateTime.js, app/components/FormattedDateTime/messages.js, app/components/SanitizedFormattedNumber/index.jsx, app/components/TransactionAmount/index.jsx, app/components/TransactionListHeader/index.jsx, app/containers/CrowdsaleDetail/index.jsx, app/containers/CrowdsaleDetail/reducer.js, app/containers/Crowdsales/index.jsx, app/containers/Crowdsales/reducer.js
* moved crowdsale utc tooltip to column header
* crowdsale transaction history sorting
* changed tooltip utc text
* rename MetaDEx to OmniDex
=> Crowdsales feedback v2

app/components/CrowdsaleInfo/index.jsx, app/components/Header/index.jsx, app/containers/App/constants.js, app/containers/App/index.jsx, app/containers/CrowdsaleDetail/index.jsx, app/containers/CrowdsaleDetail/reducer.js, app/containers/Crowdsales/index.jsx, app/containers/Crowdsales/reducer.js, app/containers/Properties/index.jsx
* desc sorting in crowdsales list
* desc sorting in crowdsale transaction list
* minor UI improvements
* removed ecosystem toggle from property list
* removed ecosystem toggle from crowdsale list
* refactoring crowdsales route to allow ecosystem in the url
* renamed constant ECOSYSTEM_PROD_NAME to `Main`
* added options crowdsale Main & Crowdsales Test ecosystem to navbar menu
* added property id to crowdsales' names
* added line-break between desired property name and property id
* added line-break to `Buy with Omniwallet` button
=> Crowdsales feedback v3

app/components/TransactionAmount/index.jsx, app/containers/Properties/index.jsx
+ rename `Assets` to `Properties`
+ removed amount toggle
=> Removed amount toggle & rename `Assets` to `Properties`

app/containers/CrowdsaleDetail/index.jsx
* force decimals for divisible tokens in crowdsale details panel
=> force decimals for divisible tokens

app/components/SanitizedFormattedNumber/index.jsx, app/components/TransactionListHeader/index.jsx, app/containers/CrowdsaleDetail/index.jsx, app/containers/Crowdsales/index.jsx
* removed the parentheses around the number of transactions/pages
* changed text in crowdsale created to `started`
* #fix use number string value to get dot position if it exists
=> Fix readability improvement

app/containers/CrowdsaleDetail/index.jsx
* added `tokens purchased`
* set current early bird bonus decimals to 3
=> Feat tokens purchased

.yarnclean, package.json, yarn.lock
+ added `svgo` package
+ excluded `svgo.yml` from .yarnclean
=> svgo build fix

app/components/TransactionHistory/index.jsx
=> history chart

app/components/Token/index.jsx, app/components/TransactionHistory/index.jsx, app/components/Wallet/index.jsx, app/components/Wallet/messages.js, app/containers/AddressDetail/index.jsx, app/containers/AddressDetail/saga.js, app/containers/AssetDetail/index.jsx, package.json, yarn.lock
+ update crosshair values on x axie movement
+ inject properties into state
+ splited balance props into right & flagged
+ update reactstrap package to `6.4.0`
=> Feat stat graph & flagged Props (logo, message & layout)

app/components/Wallet/index.jsx
* only treat as flagged tokens with duplicate, scam or replaced flags
=> #fix wallet flagged tokens

app/components/Transaction/index.jsx
+ #fix pass state to force new rouce entry and avoid click twice to g…et back
=> Fix click twice to get back

app/components/Asset/index.jsx, app/components/AssetInfo/index.jsx, app/components/CrowdsaleInfo/index.jsx, app/components/Token/index.jsx, app/components/Transaction/index.jsx, app/components/TransactionInfo/index.jsx, app/containers/AssetDetail/index.jsx, app/containers/CrowdsaleDetail/index.jsx, app/containers/Search/index.jsx
+ #fix click twice to go back
+ layout normalization
=> Click twice to go back

app/components/Transaction/index.jsx, app/responsive-styles.scss
+ token name and confirmation status aligned to left for desktop screen sizes, and centered for mobile
+ specific css class to center items into flex containers
=> Feat ux improvements

app/components/Transaction/index.jsx, app/components/Transaction/transaction.scss, app/responsive-styles.scss
+ truncate transaction id for small screens
+ removed old styles
+ added specific text-truncate rule for screen sizes small than md
+ minor mobile layout fixes & improvements
+ changes related to UX improvements feedback
+ added specific css rules to center items into flex containers
+ token name and confirmation status aligned to left for desktop screen sizes, and centered for mobile
=> Feedback ux improvements

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/MAINTAINERS.md, .github/PULL_REQUEST_TEMPLATE.md, LICENSE.md, README.md
+ added MIT license file
+ #fix app.js file path
+ added contributing guide
+ added maintainers file
+ fix file links
=> Fix license

app/components/BlockList/index.jsx, app/components/BlockList/messages.js, app/components/FormattedDateTime/index.jsx, app/components/JumpToBlock/index.jsx, app/components/ListHeader/index.jsx, app/components/NoOmniBlockTransactions/index.jsx, app/components/NoOmniBlockTransactions/messages.js, app/components/NoOmniBlockTransactions/tests/index.test.js, app/components/NoOmniBlocks/index.jsx, app/components/NoOmniBlocks/messages.js, app/components/NoOmniBlocks/tests/index.test.js, app/components/SearchBox/index.jsx, app/containers/App/constants.js, app/containers/App/index.jsx, app/containers/BlockDetail/index.jsx, app/containers/Blocks/index.jsx, app/containers/Blocks/reducer.js, app/containers/Blocks/saga.js, app/containers/Crowdsales/index.jsx, app/containers/Crowdsales/reducer.js, app/containers/FullBlockList/index.jsx, app/containers/HomePage/index.jsx
+ added margin bottom to `SearchBox` for mobile layouts
+ added tooltips to USD Value, Transactions & Timestamp column titles
+ added tooltip with USD values by property
+ added tooltip with transactions by property
+ export FormattedDateTime messages
+ reduced input box in `JumpToBlock` Component
+ added `NoOmniBlocks` and `NoOmniBlockTransactions` components
+ #refactoring to use `NoOmniBlockTransactions` and `JumpToBlock` Components in `Block Detail`
+ added `FIRST_BLOCK` constant to App
+ removed block navigation from `HomePage`
+ added block navigation
+ removed load more blocks
+ added block navigation support to `FullBlockList` route
+ #fix sort crowdsales desc by deadline
+ expanded block detail title to fit all words in the same line
=> Feedback block listing new layout

app/components/AssetInfo/index.jsx
+ Show closing date only when the asset is a crowdsale
=> + Show closing date only when the asset is a crowdsale

app/components/AssetInfo/index.jsx
=> Clean debuggers

app/components/JumpToBlock/index.jsx, app/components/NoOmniBlockTransactions/index.jsx, app/containers/BlockDetail/index.jsx
+ validate if the requested block is an omni block before to redirect
+ show a tooltip with requested block error
+ changed block not found error
=> feedback release

app/components/JumpToBlock/index.jsx, app/containers/BlockDetail/index.jsx
+ clear timeout on component unmount
+ take last block from status information to validate requested blocks
=> fix jump to block

app/components/SanitizedFormattedNumber/index.jsx
=> + #fix amount parsing

app/components/ListHeader/index.jsx, app/components/TransactionListHeader/index.jsx, app/components/TransactionListHeader/messages.js, app/containers/Transactions/index.jsx
+ added count label to transaction list header
=> #fix count list header

app/containers/Blocks/reducer.js
=> Feat sort blocks by Id

app/components/ColoredHash/index.jsx, app/containers/BlockDetail/index.jsx, app/containers/BlockDetail/messages.js
+ disable auto hide for block hashe tooltip
+ added block hash to block detail header
=> Feat hash header tooltip

app/components/CrowdsaleInfo/index.jsx, app/containers/BlockDetail/index.jsx
+ #refactoring use crowdsale flags to get logo
=> Crowdsale flags

app/components/AssetLogo/index.jsx, app/components/AssetLogo/tests/index.test.js, app/components/BlockList/index.jsx
+ added tooltip & link to asset logo
=> + added tooltip & link to asset logo

app/components/AssetLogo/index.jsx
=> Feat asset logo 

app/components/TransactionInfo/index.jsx
+ take the recipient address from purchases data when is not present in the transaction summary
=> #fix transaction recipient address

app/components/Transaction/index.jsx, app/components/TransactionInfo/index.jsx, app/utils/getTransactionHeading.js, app/utils/tests/getTransactionHeading.test.js
+ added helper to get transaction heading by type int
+ #refactoring to use getTransactionHeading helper
=> Get transaction heading by type int

app/components/Asset/index.jsx, app/components/AssetLogo/index.jsx, app/components/BlockList/index.jsx, app/components/CrowdsaleInfo/index.jsx, app/components/CrowdsaleTransaction/index.jsx, app/components/ServiceBlock/index.jsx, app/components/Token/index.jsx, app/components/Token/reducer.js, app/components/Token/selectors.js, app/components/Transaction/index.jsx, app/components/TransactionInfo/index.jsx, app/components/Wallet/index.jsx, app/containers/AssetDetail/index.jsx, app/containers/CrowdsaleDetail/index.jsx, app/containers/CrowdsaleDetail/saga.js, app/containers/Search/index.jsx, app/containers/TransactionDetail/index.jsx, app/utils/tests/getTransactionHeading.test.js
+ #refactoring show warnings (logo & message) for flagged tokens (scam, duplicated, replaced) in the whole app
+ #fix minor issues
+ clean & improve code
=> Refactoring logos & warnings

app/components/Header/index.jsx
=> Maintenance message

app/components/Header/index.jsx
=> Hide maintenance message

app/containers/CrowdsaleDetail/crowdsaledetail.scss, app/containers/CrowdsaleDetail/index.jsx, app/index.html, package.json, yarn.lock
+ added react-share to handle social media share links
+ override twitter meta tags on crowdsale detail
+ #refactoring to use `react-share` for social media sharing
=> Feat twitter card

app/components/ErrorBoundary/index.jsx, app/components/Header/index.jsx, app/containers/Activations/Loadable.js, app/containers/Activations/actions.js, app/containers/Activations/constants.js, app/containers/Activations/index.jsx, app/containers/Activations/messages.js, app/containers/Activations/reducer.js, app/containers/Activations/saga.js, app/containers/Activations/selectors.js, app/containers/Activations/tests/actions.test.js, app/containers/Activations/tests/index.test.js, app/containers/Activations/tests/reducer.test.js, app/containers/Activations/tests/saga.test.js, app/containers/Activations/tests/selectors.test.js, app/containers/App/index.jsx
+ added `Activation List` Container with inner components
+ sort by feature id asc
+ renamed column names
+ using mocked values until the service be ready
=> Feat activation link list

app/components/NoOmniBlockTransactions/messages.js, app/components/NoOmniBlocks/messages.js, app/components/NoOmniTransactions/messages.js
+ replaced links from blocktrail.com to blockchair.com
=> External links

app/components/ListPagination/index.jsx, app/containers/Transactions/actions.js, app/containers/Transactions/reducer.js, app/containers/Transactions/saga.js
+ filter unconfirmed transactions in address detail confirmed transactions section
+ added address to saga transaction load result
+ #fix background-color pagination buttons
=> Hide unconfirmed txs in Address Detail

app/components/Transaction/index.jsx, app/components/TransactionInfo/index.jsx, app/containers/Transactions/index.jsx
+ use default cursor on status boxes
+ disable confirmed/unconfirmed buttons when them are selected
=> UX Improvements

app/components/JumpToBlock/index.jsx, app/containers/BlockDetail/index.jsx, app/containers/BlockDetail/messages.js
+ #refactoring added dropdown for valid, invalid transactions
=> Feat txs status dropdown

app/containers/BlockDetail/blockdetail.scss, app/containers/BlockDetail/constants.js, app/containers/BlockDetail/index.jsx
+ added filter to show all, valid or invalid transactions
=> Transaction filter

app/components/BlockList/index.jsx
+ removed asset resolution in block listing
=> + removed asset resolution in block listing

app/components/ErrorBoundary/index.jsx
+ removed modal error title
+ replaced `Try again` message
=> Modal error texts

app/components/ListHeader/index.jsx, app/containers/Transactions/index.jsx, app/containers/Transactions/messages.js, yarn.lock
+ updated unconfirmed transactions list header
+ meaning improvement of transaction list title
+ updated yarn.lock
=> Feat unconfirmed txs title

app/components/TransactionHistory/index.jsx
+ added series legend to crosshair
=> Feat chart items legend

.dependabot/config.yml
+ added dependabot config to manage security updates automatically
=> + added  dependabot config to manage security updates automatically

app/containers/CrowdsaleDetail/reducer.js
+ desc sorting of crodwsale transactions
=> Desc sorting of crodwsale transactions

app/components/BlockPagination/index.jsx, app/components/ClientSidePagination/index.jsx, app/components/ClientSidePagination/tests/index.test.js, app/components/ListPagination/index.jsx, app/components/SearchBox/index.jsx, app/components/Wallet/index.jsx, app/containers/BlockDetail/index.jsx, app/containers/BlockDetail/messages.js, app/containers/Search/index.jsx, app/containers/Transactions/index.jsx, app/containers/Transactions/reducer.js
+ added `ClientSidePagination` component
+ #fix pagination when block detail has 100 transactions
+ added client side pagination to unconfirmed transactions
+ added transations count to block detail header …
+ #fix load page based on url params
+ #fix page count on BlockDetail
+ sort balance properties by id
+ rename Prev/Next to Prev Block/Next Block to improve meaning
+ added Prev/Next block navigation to above of transactions list
+ #fix search transaction
+ #fix update query value on change
+ minor style fixes and improvements
+ clean code
=> Release v4 fixes and feedback

app/components/Transaction/index.jsx, app/components/Wallet/index.jsx, app/containers/AddressDetail/index.jsx, app/containers/BlockDetail/index.jsx, app/containers/Transactions/index.jsx, app/containers/Transactions/reducer.js, app/reducers.js
+ #fix block detail pagination index
+ moved transactions reducer injection to `Transactions` Component
+ #fix unconfirmed and address transactions pagination
+ #fix property sorting for wallet balances
+ clean code
=> Pagination fixes

app/components/Token/actions.js, app/components/Token/constants.js, app/components/Token/index.jsx, app/components/Token/reducer.js, app/components/Token/saga.js, app/components/Token/selectors.js, app/components/Transaction/index.jsx, app/components/Wallet/index.jsx, app/containers/AddressDetail/index.jsx, app/containers/BlockDetail/index.jsx, app/containers/Transactions/index.jsx, app/containers/Transactions/reducer.js, app/reducers.js
+ #refactoring use new bulk endpoint to avoid rate limiting
=> Feat token bulk fetch

app/components/FooterLinks/index.jsx, app/components/TransactionListHeader/index.jsx, app/containers/Transactions/index.jsx
+ #refactoring `TransactionListHeader` to function component
+ #fix unconfirmed transactions count
+ force page reload when clicked `Show all unconfirmed transactions`, `Full block list` links
=> Fix unconfirmed txs headers

app/components/ListPagination/index.jsx, app/containers/BlockDetail/index.jsx, app/containers/Transactions/index.jsx, app/containers/Transactions/reducer.js, app/utils/getMaxPagesByMedia.js
+ added helper to get the max navigation page count by media device width
+ #refactoring to `getMaxPagesByMedia()`helper
+ #fix set of current data on page change, the calculation of items get the right quantity of transactions to show
=> Fix blocks txs pagination

app/containers/BlockDetail/index.jsx, app/containers/Transactions/index.jsx
+ #fix assign data only when current block detail transactions was loaded
+ #fix pagination results calculation for unconfirmed transactions
=> Fix pagination result calculation

app/containers/App/constants.js
+ added feature activation `15` to constants
=> Added feature activation to constants

app/containers/App/index.jsx
Reverts OmniLayer/omniexplorer#351
=> Revert "+ redirect to static 404 page when route is not found"

app/containers/Transactions/actions.js, app/containers/Transactions/index.jsx, app/containers/Transactions/reducer.js, app/containers/Transactions/saga.js
+ recovery `txcount` from service result
+ show transaction quantity on transaction list header
=> Show transaction count 

app/components/SearchBox/index.jsx, app/containers/Search/saga.js
=> #fix testnet address search

app/components/ColoredHash/index.jsx, app/components/Menu/index.js, app/components/Menu/menu.scss, app/components/MenuButton/index.js, app/components/TestnetMarquee/index.js, app/components/TestnetMarquee/testnetmarquee.scss
+ avoid to use black color in hash pills
+ close on click outside of menu
+ #fix Menu styles on dark mode
+ improved styles of testnet marquee
=> Fix styles and behaviors

app/components/AssetInfo/index.jsx, app/components/Menu/index.js, app/components/TransactionInfo/index.jsx, app/containers/Transactions/saga.js
+ #fix calculation of page number in exodus transaction requests
+ #fix raw asset data url
+ #fix open raw asset data in new tab
+ #fix raw transaction data url
+ changed toggle switch environment shortcut `[shift-ctrl-t]` => `[shift-ctrl-alt-t]`
=> Fixes oe v4

app/components/ExodusTransaction/index.js, app/components/StyledLink/index.js, app/components/Transaction/index.jsx, app/containers/Transactions/reducer.js, app/containers/Transactions/saga.js
+ exodus transactions new styling
+ #fix Exodus txs page count
+ #fix Exodus txs mapping
+ #fix Exodus txs UI
+ #fix disable Link pointer events when it's disabled
+ #fix changed amount type to any, because it can receive strings & numbers
=> Feat style exodustx

app/components/BlockPagination/index.jsx, app/components/ClassABTransaction/index.js, app/components/ColoredHash/index.jsx, app/components/ContainerBase/index.jsx, app/components/CrowdsaleTransaction/index.jsx, app/components/StyledIconCopy/index.js, app/components/Transaction/index.jsx, app/components/TransactionHistory/index.jsx, app/containers/App/index.jsx, app/theming/theming-modes.scss, package-lock.json, package.json
+ added `react-virtualized` package to use AutoSizer`
+ #fix removed horizontal scroll
+ memoize `ColoredHash
+ added styles to `StyledIconCopy` for ligth & dark modes
=> Fix horizontal scroll

app/containers/Transactions/index.jsx
+ #fix calculation of txs results by page on mobile
=> Hotfix show address transactions on mobile

app/components/Asset/index.jsx, app/components/AssetInfo/index.jsx, app/components/ClassABTransaction/index.js, app/components/CrowdsaleTransaction/index.jsx, app/components/JumpToBlock/index.jsx, app/components/Menu/index.js, app/components/ServiceBlock/index.jsx, app/components/StyledIconCopy/index.js, app/components/Transaction/index.jsx, app/components/Transaction/transaction.scss, app/components/TransactionInfo/index.jsx, app/components/Wallet/index.jsx, app/containers/BlockDetail/index.jsx, app/containers/BlockDetail/messages.js, app/containers/Blocks/index.jsx, app/containers/Search/index.jsx, app/containers/Search/saga.js, app/containers/Transactions/index.jsx, app/containers/Transactions/messages.js, app/global-styles.js, app/theming/theming-modes.scss
* #fix automatically go to the first Omni block if the number entered is less than the first Omni block number
* #fix added title for class A/B txs
=> Fixes release v4

app/components/AssetInfo/index.jsx, app/components/ClassABTransaction/index.js, app/components/CrowdsaleTransaction/index.jsx, app/components/Token/reducer.js, app/components/Token/saga.js, app/components/Transaction/index.jsx, app/components/TransactionInfo/index.jsx, package-lock.json, package.json
+ added missing switch breaks
+ update property data on API get-token reponse
+ check and remove for spaces from strings used to target DOM elements by id
+ remove HTML link from issuer address when it's not a valid address (like BTC with `Satoshi Nakamoto` as issuer address)
+ updated RC version to 5.0.1
=> Rc 5.0.1 fixes

app/containers/AddressDetail/saga.js, app/containers/Search/saga.js, package-lock.json, package.json
+ #fix get BTC balance from external services
+ version "5.0.2"
=> RC 5.0.2 #fixes

app/components/ListPagination/index.jsx, app/containers/AddressDetail/index.jsx, app/containers/Transactions/index.jsx
+ show scroll on pagination buttons when it overflow screen
+ avoid break line on pagination buttons
+ take current page parameter from url parameters on `AddressDetail`
+ #fix pagination on history back
=> Rc 5.0.4 fixes

app/components/List/index.jsx, app/components/Menu/index.js
+ hide mainnet/testnet toogle
+ added separator between transactions (Block transactions, Address transactions & unconfirmed transactions)
=> Rc 5.0.5 feedback

app/components/BlockPagination/index.jsx, app/containers/BlockDetail/index.jsx
+ disable prev block pagination if the current is the first Omni block
+ show a message when it's the first Omni block
=> RC 5.0.6 feedback

app/components/CrowdsaleInfo/index.jsx, app/components/GrayArrowDown/index.js, app/components/GreenArrowDown/index.js, app/components/Transaction/index.jsx, app/containers/Crowdsales/index.jsx
+ align decimal points in tabular lists
+ fix arrow down styles
=> styles fixing

app/components/ClientSidePagination/index.jsx, app/components/ListPagination/index.jsx, app/components/StyledA/index.js, app/components/StyledLink/index.js, app/containers/Blocks/index.jsx, package-lock.json, package.json
+ removed horizontal scroll on pages using `ListPagination` & `ClientSidePagination` components
+ #fix link primary colors on light-mode
+ updated OE to version 5.1.1
=> feat styles

app/containers/BlockDetail/index.jsx
+ changed sentences order to avoid build issue that use the assignment as a condition
=> Fix load txs on jump to block

app/app.js, app/components/BlockPagination/index.jsx, package.json
+ added app version logging
+ moved StyledComponent creation outside of function component
+ updated version to `5.1.3`
=> app version logging

package-lock.json, package.json
=> + update project dependencies

app/components/AssetLogo/index.jsx, app/components/SearchBox/index.jsx, app/components/Transaction/index.jsx, app/components/Transaction/transaction.scss, app/components/TransactionAmount/MetaDExAmount.js, app/containers/Search/index.jsx, app/containers/Search/reducer.js
+ allow special characters on search criteria
+ added propertyname to token name resolution in AssetLogo
+ hide tx heading prop name for Crowdsale purchases
+ normalized font-size to 1.25 rem for all txs
+ #fix required props on MetaDExAmount component
=> Fix search parameters

app/components/LinkPreview/FactoryLinkPreview.js, app/components/LinkPreview/index.js, app/components/LinkPreview/tests/index.test.js, app/components/TransactionAmount/TransactionAmountTitleFactory.js, app/components/TransactionAmount/index.jsx, app/components/TransactionInfo/index.jsx, app/containers/Activations/index.jsx, app/containers/AddressDetail/index.jsx, app/containers/AssetDetail/index.jsx, app/containers/BlockDetail/index.jsx, app/containers/CrowdsaleDetail/index.jsx, app/containers/Crowdsales/index.jsx, app/containers/Properties/index.jsx, package-lock.json, package.json
+ #refactoring build custom link preview based on page content
=> Feat custom link preview

app/components/AssetInfo/index.jsx, app/components/TransactionInfo/index.jsx
+ show ecosystem on transaction detail
+ renamed `Raw Data` to `JSON Data`
=> Show ecosystem on tx detail

app/components/EcosystemLogo/index.js, app/components/HeaderBrand/index.js, app/components/NoOmniTransactions/messages.js, app/components/ServiceBlock/ServiceBlockLogo.js, app/containers/AddressDetail/saga.js, app/containers/App/constants.js, app/containers/App/index.jsx, app/containers/BlockDetail/messages.js, app/containers/Search/saga.js, app/utils/getLocationPath.js, app/utils/getLogo.js, app/utils/isLTC.js, app/utils/isOmniExplorer.js, app/utils/isOmniLite.js, package-lock.json, package.json
+ #refactoring renamed `omnilite` to `ltc`
+ clean code
+ updated version to `6.1.1`
=> Refactoring "omnilite" to "ltc"

app/components/Footer/index.jsx, app/containers/App/index.jsx
+ changed background-color
+ fixed footer to bottom page
=> + pulish footer section

app/components/TransactionHistory/index.jsx, package-lock.json, package.json
+ hide tx value on history chart for FTC & LTC
+ hide vertical bar of tx value for FTC & LTC
+ updated version to "6.2.2"
=> Hide tx value on history chart for FTC & LTC

app/components/Footer/index.jsx, package-lock.json, package.json
+ added Data provider link
+ added app version
=> Footer improvement

app/components/TransactionAmount/DExPurchaseAmount.js, app/components/TransactionAmount/TransactionAmountTitleFactory.js, app/components/TransactionInfo/index.jsx, package-lock.json, package.json
+ #refactoring resolve asset paid by current blockchain
+ #fix removed tx action 
+ clean code
+ version v6.5.5
=> Fix tx type label

app/components/AssetInfo/index.jsx, package-lock.json, package.json
=> + #fix missing const

app/components/ErrorBoundary/index.jsx, app/components/Token/saga.js, app/containers/Blocks/index.jsx
+ #fix handle property not found 
+ #fix error boundary links (homepage, retry)
+ #fix changed showEmptySwitch event, onClick to onChange
=> Handle property not found

app/components/EmptyBlockMessage/index.js, app/components/EmptyBlockMessage/messages.js, app/components/NoOmniBlockTransactions/index.jsx, app/components/NoOmniBlockTransactions/messages.js, app/components/NoOmniBlocks/index.jsx, app/components/NoOmniBlocks/messages.js, app/components/NoOmniTransactions/index.jsx, app/components/NoOmniTransactions/messages.js, app/utils/getBlockchainName.js, package-lock.json, package.json
+ customization of empty messages based on blockchain 
+ update dependency engines to node: ">=12.13.0" & npm: ">=7"
+ updated OE version to 7.0.0
+ node >=12.13
+ npm >=7
=> Version 7.0.0

app/components/CrowdsaleInfo/index.jsx, package-lock.json, package.json
+ #fix show `Buy with Omniwallet` only for Omni crowdsales
+ updated version to 7.0.1
=> Show `Buy with Omniwallet` only for Omni crowdsales

package-lock.json, package.json
=> Omniexplorer v7.2.0

internals/webpack/webpack.base.babel.js, package-lock.json, package.json, server/middlewares/addDevMiddlewares.js
+ #refactoring image-loader webpack options
+ #refactoring const http-proxy-middleware
+ v7.3.2
=> + #refactoring image-loader webpack options
